# Generated by Django 4.2 on 2024-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_application_is_training_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('family_members', models.IntegerField()),
                ('monthly_income', models.IntegerField()),
                ('credit_history', models.IntegerField()),
                ('loan_type', models.IntegerField()),
                ('loan_term', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
                ('mortgage_type', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_training_data',
        ),
    ]
