# Generated by Django 6.0.3 on 2026-03-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_auto_20240317_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expected_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='family_members',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_term',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='monthly_income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='family_members',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='loan_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='loan_term',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='monthly_income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
