# Generated by Django 6.0.3 on 2026-04-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_application_expected_profit_alter_application_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('Bachelors', 'Bachelors Degree'), ('Masters', 'Masters Degree'), ('PhD', 'PhD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='existing_loans_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='existing_monthly_payments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='has_guarantor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='loan_purpose',
            field=models.CharField(blank=True, choices=[('Debt Consolidation', 'Debt Consolidation'), ('Home Improvement', 'Home Improvement'), ('Business', 'Business'), ('Student Loan', 'Student Loan'), ('Medical Expenses', 'Medical Expenses')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='monthly_expenses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='other_monthly_income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='work_experience_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='education_level',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('Bachelors', 'Bachelors Degree'), ('Masters', 'Masters Degree'), ('PhD', 'PhD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Unemployed', 'Unemployed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='existing_loans_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='existing_monthly_payments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='has_guarantor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='loan_purpose',
            field=models.CharField(blank=True, choices=[('Debt Consolidation', 'Debt Consolidation'), ('Home Improvement', 'Home Improvement'), ('Business', 'Business'), ('Student Loan', 'Student Loan'), ('Medical Expenses', 'Medical Expenses')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='monthly_expenses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='other_monthly_income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='work_experience_months',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
