# Generated by Django 6.0.3 on 2026-04-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_application_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, choices=[('High School', 'Միջնակարգ'), ('Bachelors', 'Բակալավր'), ('Masters', 'Մագիստրոս'), ('PhD', 'Դոկտոր')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Լրիվ դրույք'), ('Part-time', 'Կես դրույք'), ('Self-employed', 'Ինքնազբաղված'), ('Unemployed', 'Գործազուրկ')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='loan_purpose',
            field=models.CharField(blank=True, choices=[('Debt Consolidation', 'Վարկերի միավորում'), ('Home Improvement', 'Տան վերանորոգում'), ('Business', 'Բիզնես'), ('Student Loan', 'Ուսանողական վարկ'), ('Medical Expenses', 'Բժշկական ծախսեր'), ('Other', 'Այլ')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Ամուսնացած չէ'), ('Married', 'Ամուսնացած'), ('Divorced', 'Ամուսնալուծված'), ('Widowed', 'Այրի')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='education_level',
            field=models.CharField(blank=True, choices=[('High School', 'Միջնակարգ'), ('Bachelors', 'Բակալավր'), ('Masters', 'Մագիստրոս'), ('PhD', 'Դոկտոր')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Լրիվ դրույք'), ('Part-time', 'Կես դրույք'), ('Self-employed', 'Ինքնազբաղված'), ('Unemployed', 'Գործազուրկ')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='loan_purpose',
            field=models.CharField(blank=True, choices=[('Debt Consolidation', 'Վարկերի միավորում'), ('Home Improvement', 'Տան վերանորոգում'), ('Business', 'Բիզնես'), ('Student Loan', 'Ուսանողական վարկ'), ('Medical Expenses', 'Բժշկական ծախսեր'), ('Other', 'Այլ')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Ամուսնացած չէ'), ('Married', 'Ամուսնացած'), ('Divorced', 'Ամուսնալուծված'), ('Widowed', 'Այրի')], max_length=20, null=True),
        ),
    ]
