# Generated by Django 6.0.3 on 2026-04-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_alter_application_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='loan_purpose',
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='loan_purpose',
        ),
    ]
